#!/apollo/bin/env sh
 
# Runs before 100ShutdownProcessManager
 
for logname in PMAdmin.log; do
    "${APOLLO_ENVIRONMENT_ROOT}/bin/cronolog-rotate-log-hourly-unblock.sh" \
    "${APOLLO_ENVIRONMENT_ROOT}/var/output/logs/$logname"
done
